"""Run QA0.1 inventory-complete integrity audit."""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from business_cycle.audits.qa0_integrity_audit import (  # noqa: E402
    QA0IntegrityAuditError,
    run_qa0_integrity_audit,
)


def main() -> int:
    try:
        summary = run_qa0_integrity_audit()
    except QA0IntegrityAuditError as exc:
        print(f"error={exc}", file=sys.stderr)
        return 1
    ordered_fields = [
        "phase",
        "audit_status",
        "canonical_requirement_count",
        "traceability_row_count",
        "missing_traceability_requirement_count",
        "duplicate_traceability_requirement_count",
        "unknown_traceability_requirement_count",
        "discovered_formal_indicator_count",
        "discovered_experimental_indicator_count",
        "discovered_unique_indicator_count",
        "mapped_indicator_count",
        "unmapped_indicator_count",
        "discovered_direct_series_count",
        "discovered_derived_series_count",
        "discovered_unique_series_count",
        "audited_series_count",
        "unaudited_series_count",
        "release_lag_registry_series_count",
        "series_without_release_lag_registry_count",
        "series_without_temporal_status_count",
        "provenance_mapped_indicator_count",
        "provenance_unmapped_indicator_count",
        "orphaned_implementation_path_count",
        "duplicate_inventory_id_count",
        "duplicate_series_alias_count",
        "book_sourced_requirement_count",
        "official_data_semantics_requirement_count",
        "modern_methodology_requirement_count",
        "project_safety_requirement_count",
        "book_core_requirement_count",
        "book_supporting_requirement_count",
        "not_book_requirement_count",
        "modern_methodology_marked_book_core_count",
        "taxonomy_misclassification_count",
        "canonical_book_indicator_requirement_count",
        "phase_role_indicator_coverage_row_count",
        "duplicate_finding_id_count",
        "duplicate_requirement_finding_count",
        "book_indicator_manifest_count",
        "book_indicator_coverage_row_count",
        "missing_book_indicator_coverage_row_count",
        "hard_coded_summary_value_count",
        "inventory_drift_detection_ready",
        "traceability_drift_detection_ready",
        "series_drift_detection_ready",
        "provenance_drift_detection_ready",
        "qa0_inventory_complete",
        "book_core_row_count",
        "book_core_missing_count",
        "book_core_conflicting_count",
        "book_core_coverage_ratio",
        "book_alignment_claim_allowed",
        "audited_series_count",
        "availability_metadata_complete_count",
        "series_missing_availability_metadata_count",
        "series_without_temporal_status_count",
        "exact_vintage_supported_series_count",
        "initial_release_only_series_count",
        "release_lag_proxy_series_count",
        "unsupported_series_count",
        "release_lag_proxy_misclassified_as_point_in_time_count",
        "revised_data_only",
        "vintage_data_supported",
        "point_in_time_backtest_ready",
        "temporal_leakage_blocker_count",
        "cached_series_count",
        "formal_indicator_count",
        "formal_direct_dependency_count",
        "formal_leaf_direct_dependency_count",
        "formal_derived_output_count",
        "formal_exact_vintage_dependency_count",
        "formal_missing_vintage_dependency_count",
        "formal_scenario_as_of_date_count",
        "formal_leaf_total_pair_count",
        "formal_leaf_covered_pair_count",
        "formal_leaf_missing_pair_count",
        "formal_leaf_coverage_ratio",
        "formal_derived_output_total_pair_count",
        "formal_derived_candidate_pair_count",
        "formal_derived_strict_covered_pair_count",
        "formal_derived_strict_coverage_ratio",
        "formal_total_coverage_pair_count",
        "formal_leaf_total_coverage_pair_count",
        "formal_derived_total_coverage_pair_count",
        "formal_covered_pair_count",
        "formal_missing_pair_count",
        "formal_leaf_covered_pair_count",
        "formal_leaf_missing_pair_count",
        "formal_derived_covered_pair_count",
        "formal_derived_missing_pair_count",
        "candidate_derived_snapshot_count",
        "provisional_derived_snapshot_count",
        "provisional_snapshot_counted_as_strict_count",
        "formal_indicator_output_counting_ready",
        "formal_proxy_pair_count",
        "formal_initial_release_only_pair_count",
        "formal_revised_fallback_pair_count",
        "formal_invalid_realtime_interval_count",
        "strict_snapshot_validation_failure_count",
        "exact_vintage_covered_pair_count",
        "release_archive_covered_pair_count",
        "observational_archive_covered_pair_count",
        "derived_point_in_time_covered_pair_count",
        "duplicate_temporal_pair_id_count",
        "derived_output_double_count_count",
        "denominator_semantics_valid",
        "formal_scenario_as_of_coverage_ratio",
        "date_local_strict_ready_snapshot_count",
        "partial_horizon_strict_ready_series_count",
        "full_horizon_blocked_but_date_local_ready_series_count",
        "series_with_authoritative_cache_count",
        "series_with_valid_manifest_count",
        "series_with_segmented_cache_count",
        "segment_merge_failure_count",
        "dgs10_required_pair_count",
        "dgs10_covered_pair_count",
        "dgs10_missing_pair_count",
        "dgs10_coverage_ratio",
        "dgs10_partial_horizon_ready",
        "dgs10_full_required_horizon_ready",
        "blocker_class",
        "official_query_supported_series_count",
        "official_query_attempted_series_count",
        "official_query_succeeded_series_count",
        "official_query_failed_series_count",
        "partial_vintage_history_series_count",
        "full_required_horizon_exact_vintage_series_count",
        "full_required_horizon_archive_reconstructed_series_count",
        "full_required_horizon_observational_series_count",
        "full_required_horizon_strict_ready_series_count",
        "history_insufficient_series_count",
        "provider_full_range_failed_series_count",
        "unresolved_formal_series_count",
        "registry_declared_exact_vintage_series_count",
        "live_verified_exact_vintage_series_count",
        "live_verified_initial_release_series_count",
        "live_verified_unsupported_series_count",
        "live_verified_history_insufficient_series_count",
        "point_in_time_selector_ready",
        "formal_phase_point_in_time_ready",
        "golden_benchmark_point_in_time_ready",
        "no_silent_revised_fallback",
        "strict_complete_scenario_count",
        "strict_partial_scenario_count",
        "revised_diagnostic_only_scenario_count",
        "unsupported_scenario_count",
        "strict_complete_as_of_pair_count",
        "strict_partial_as_of_pair_count",
        "missing_as_of_pair_count",
        "temporally_eligible_for_phase_diagnostics_scenario_count",
        "temporally_eligible_for_parameter_calibration_scenario_count",
        "temporally_eligible_for_validation_scenario_count",
        "temporally_eligible_for_performance_backtest_scenario_count",
        "methodologically_eligible_for_development_scenario_count",
        "methodologically_eligible_for_parameter_calibration_scenario_count",
        "methodologically_eligible_for_validation_scenario_count",
        "methodologically_eligible_for_untouched_holdout_scenario_count",
        "methodologically_eligible_for_performance_backtest_scenario_count",
        "final_calibration_eligible_scenario_count",
        "final_validation_eligible_scenario_count",
        "final_untouched_holdout_eligible_scenario_count",
        "final_performance_backtest_eligible_scenario_count",
        "book_benchmark_eligible_scenario_count",
        "ambiguous_eligibility_field_count",
        "unscoped_calibration_flag_count",
        "unscoped_validation_flag_count",
        "unscoped_performance_flag_count",
        "scenario_with_silent_horizon_reduction_count",
        "incomplete_strict_phase_decision_count",
        "incomplete_strict_resolver_input_count",
        "partial_score_without_diagnostic_label_count",
        "qa1_inventory_complete",
        "qa1_temporal_modes_ready",
        "qa1_strict_selector_ready",
        "qa1_no_silent_fallback",
        "qa1_scenario_eligibility_ready",
        "qa1_strict_abstention_ready",
        "qa1_formal_phase_decision_gate_ready",
        "full_formal_history_ready",
        "partial_strict_scenario_set_ready",
        "book_benchmark_temporal_ready",
        "real_backtest_temporal_ready",
        "qa2_allowed",
        "qa2_performance_backtest_allowed",
        "qa2_parameter_calibration_allowed",
        "qa1_closure_status",
        "cashflow_aware_metrics_defined",
        "external_cashflow_guard_enabled",
        "unitized_nav_drawdown_defined",
        "book_cashflow_methodology_ready",
        "simple_cagr_misuse_blocked",
        "previously_seen_scenario_count",
        "untouched_holdout_scenario_count",
        "calibration_holdout_ready",
        "out_of_sample_claim_allowed",
        "external_context_dependency_detected",
        "data_only_model_validated",
        "context_ablation_ready",
        "book_indicator_count",
        "missing_book_core_count",
        "modern_extension_count",
        "golden_strategy_count",
        "book_benchmark_spec_ready",
        "book_benchmark_execution_allowed",
        "formal_regime_layer_ready",
        "regime_aware_portfolio_policy_ready",
        "shock_overlay_spec_ready",
        "formal_shock_runtime_ready",
        "dashboard_semantics_ready",
        "phase_9b_synthetic_harness_valid",
        "phase_9b_economic_validation_claim_allowed",
        "p0_finding_count",
        "p1_finding_count",
        "p2_finding_count",
        "untriaged_finding_count",
        "p0_without_blocking_gate_count",
        "unsupported_claim_count",
        "real_backtest_progression_allowed",
        "phase_9b1_allowed",
        "recommended_next_phase",
        "result",
    ]
    for field in ordered_fields:
        print(f"{field}={_format_value(summary[field])}")
    return 0


def _format_value(value: object) -> str:
    if isinstance(value, bool):
        return str(value).lower()
    return str(value)


if __name__ == "__main__":
    raise SystemExit(main())
