"""Backtest scenario specs and catalog loading."""

from business_cycle.backtests.attribution import (
    attribution_quality_counts,
    build_transition_attribution,
    write_transition_attribution,
)
from business_cycle.backtests.attribution_smoke import (
    AttributionSmokeError,
    build_attribution_smoke_summary,
    run_attribution_smoke,
)
from business_cycle.backtests.book_gap import (
    BookIndicatorGapAnalysis,
    BookIndicatorGapAnalysisError,
    high_priority_count as high_priority_book_gap_count,
    load_book_indicator_gap_analysis,
    sensitivity_issues,
    validate_book_indicator_gap_analysis,
)
from business_cycle.backtests.book_indicator_plan import (
    BookAlignedIndicatorImplementationPlan,
    BookAlignedIndicatorImplementationPlanError,
    high_priority_indicator_count,
    load_book_aligned_indicator_implementation_plan,
    purpose_groups,
    validate_book_aligned_indicator_implementation_plan,
)
from business_cycle.backtests.breadth_sensitivity import (
    BreadthSensitivityError,
    BreadthSensitivityMatrix,
    build_breadth_sensitivity_summary,
    load_breadth_sensitivity_matrix,
    run_breadth_sensitivity_experiment,
    validate_breadth_sensitivity_matrix,
    write_breadth_sensitivity_summary,
)
from business_cycle.backtests.boom_ending_candidates import (
    BoomEndingCandidateSpec,
    check_boom_ending_candidate_coverage,
    load_boom_ending_candidate_indicators,
    score_boom_ending_candidate_indicators,
    validate_boom_ending_candidate_indicators,
    write_boom_ending_candidate_scores,
)
from business_cycle.backtests.boom_ending_attribution import (
    BoomEndingAttributionError,
    build_boom_ending_attribution,
    build_boom_ending_attribution_from_file,
    write_boom_ending_attribution,
)
from business_cycle.backtests.boom_ending_diagnostics import (
    BoomEndingDiagnosticsError,
    build_boom_ending_diagnostics,
    build_boom_ending_group_summary,
    build_boom_ending_point_summary,
    is_boom_ending_high_signal,
    is_boom_ending_strong_signal,
    load_boom_ending_diagnostic_windows,
    write_boom_ending_diagnostics,
)
from business_cycle.backtests.boom_ending_refinement import (
    BoomEndingRefinementPlan,
    BoomEndingRefinementPlanError,
    high_priority_refinement_count,
    load_boom_ending_refinement_plan,
    validate_boom_ending_refinement_plan,
)
from business_cycle.backtests.candidate_indicators import (
    CandidateIndicatorError,
    RecessionConfirmationCandidateSpec,
    load_recession_confirmation_candidate_indicators,
    score_candidate_indicators,
    validate_recession_confirmation_candidate_indicators,
    write_candidate_indicator_scores,
)
from business_cycle.backtests.candidate_data import (
    CandidateDataUpdateResult,
    candidate_fred_series_ids,
    update_candidate_fred_cache,
)
from business_cycle.backtests.candidate_recession_diagnostics import (
    CandidateRecessionDiagnosticsError,
    build_candidate_point_summary,
    build_candidate_recession_diagnostics,
    build_group_summary,
    is_high_signal,
    is_strong_signal,
    load_candidate_recession_diagnostic_windows,
    write_candidate_recession_diagnostics,
)
from business_cycle.backtests.candidate_recession_rule import (
    CandidateRecessionConfirmationRule,
    CandidateRecessionRuleError,
    build_candidate_recession_rule_report,
    classify_candidate_recession_status,
    evaluate_candidate_recession_confirmation,
    load_candidate_recession_confirmation_rule,
    write_candidate_recession_rule_report,
)
from business_cycle.backtests.candidate_recession_overlay import (
    CandidateRecessionOverlayError,
    build_candidate_recession_overlay_report,
    load_candidate_recession_overlay_experiment,
    write_candidate_recession_overlay_report,
)
from business_cycle.backtests.candidate_recession_integration import (
    CandidateRecessionIntegrationDesign,
    CandidateRecessionIntegrationDesignError,
    integration_mode_allowed,
    load_candidate_recession_integration_design,
    validate_candidate_recession_integration_design,
)
from business_cycle.backtests.calibration import (
    CalibrationPlan,
    CalibrationPlanError,
    load_calibration_plan,
    validate_calibration_plan,
)
from business_cycle.backtests.calibration_experiment import (
    CalibrationExperimentError,
    build_calibration_experiment_summary,
    run_calibration_experiment,
)
from business_cycle.backtests.calibration_review import (
    CalibrationReviewError,
    build_calibration_acceptance_review,
    write_calibration_acceptance_review,
)
from business_cycle.backtests.covid_false_positive import (
    CovidFalsePositiveError,
    build_covid_false_positive_diagnostic,
    write_covid_false_positive_diagnostic,
)
from business_cycle.backtests.full_horizon_calibration import (
    run_full_horizon_calibration,
    write_full_horizon_calibration_outputs,
)
from business_cycle.backtests.catalog import (
    get_scenario,
    load_backtest_scenario_catalog,
    load_backtest_scenarios,
)
from business_cycle.backtests.specs import (
    BacktestScenario,
    BacktestScenarioCatalog,
    BacktestScenarioError,
)
from business_cycle.backtests.runner import (
    BacktestPeriodResult,
    BacktestRunConfig,
    BacktestRunResult,
    generate_monthly_periods,
    run_backtest,
)
from business_cycle.backtests.report import build_backtest_report, write_backtest_report
from business_cycle.backtests.smoke import (
    BacktestSmokeError,
    build_backtest_smoke_summary,
    run_backtest_smoke,
)

__all__ = [
    "BacktestPeriodResult",
    "BacktestRunConfig",
    "BacktestRunResult",
    "BacktestScenario",
    "BacktestScenarioCatalog",
    "BacktestScenarioError",
    "BacktestSmokeError",
    "AttributionSmokeError",
    "BookIndicatorGapAnalysis",
    "BookIndicatorGapAnalysisError",
    "BookAlignedIndicatorImplementationPlan",
    "BookAlignedIndicatorImplementationPlanError",
    "BreadthSensitivityError",
    "BreadthSensitivityMatrix",
    "BoomEndingCandidateSpec",
    "BoomEndingAttributionError",
    "BoomEndingDiagnosticsError",
    "BoomEndingRefinementPlan",
    "BoomEndingRefinementPlanError",
    "CalibrationPlan",
    "CalibrationPlanError",
    "CalibrationExperimentError",
    "CalibrationReviewError",
    "CandidateIndicatorError",
    "CandidateDataUpdateResult",
    "CandidateRecessionDiagnosticsError",
    "CandidateRecessionConfirmationRule",
    "CandidateRecessionRuleError",
    "CandidateRecessionOverlayError",
    "CandidateRecessionIntegrationDesign",
    "CandidateRecessionIntegrationDesignError",
    "CovidFalsePositiveError",
    "RecessionConfirmationCandidateSpec",
    "attribution_quality_counts",
    "build_attribution_smoke_summary",
    "build_backtest_smoke_summary",
    "build_backtest_report",
    "build_calibration_experiment_summary",
    "build_calibration_acceptance_review",
    "build_covid_false_positive_diagnostic",
    "build_breadth_sensitivity_summary",
    "build_boom_ending_diagnostics",
    "build_boom_ending_group_summary",
    "build_boom_ending_point_summary",
    "build_boom_ending_attribution",
    "build_boom_ending_attribution_from_file",
    "build_candidate_point_summary",
    "build_candidate_recession_diagnostics",
    "build_candidate_recession_rule_report",
    "build_candidate_recession_overlay_report",
    "build_group_summary",
    "build_transition_attribution",
    "candidate_fred_series_ids",
    "check_boom_ending_candidate_coverage",
    "classify_candidate_recession_status",
    "evaluate_candidate_recession_confirmation",
    "generate_monthly_periods",
    "get_scenario",
    "high_priority_book_gap_count",
    "high_priority_indicator_count",
    "high_priority_refinement_count",
    "is_high_signal",
    "is_strong_signal",
    "is_boom_ending_high_signal",
    "is_boom_ending_strong_signal",
    "integration_mode_allowed",
    "load_book_indicator_gap_analysis",
    "load_book_aligned_indicator_implementation_plan",
    "load_breadth_sensitivity_matrix",
    "load_boom_ending_candidate_indicators",
    "load_boom_ending_diagnostic_windows",
    "load_boom_ending_refinement_plan",
    "load_calibration_plan",
    "load_backtest_scenario_catalog",
    "load_backtest_scenarios",
    "load_candidate_recession_diagnostic_windows",
    "load_candidate_recession_confirmation_rule",
    "load_candidate_recession_overlay_experiment",
    "load_candidate_recession_integration_design",
    "load_recession_confirmation_candidate_indicators",
    "purpose_groups",
    "run_attribution_smoke",
    "run_backtest",
    "run_backtest_smoke",
    "run_calibration_experiment",
    "run_full_horizon_calibration",
    "run_breadth_sensitivity_experiment",
    "score_boom_ending_candidate_indicators",
    "score_candidate_indicators",
    "sensitivity_issues",
    "update_candidate_fred_cache",
    "write_transition_attribution",
    "write_calibration_acceptance_review",
    "write_covid_false_positive_diagnostic",
    "write_full_horizon_calibration_outputs",
    "validate_calibration_plan",
    "validate_book_indicator_gap_analysis",
    "validate_book_aligned_indicator_implementation_plan",
    "validate_breadth_sensitivity_matrix",
    "validate_boom_ending_candidate_indicators",
    "validate_boom_ending_refinement_plan",
    "validate_candidate_recession_integration_design",
    "validate_recession_confirmation_candidate_indicators",
    "write_backtest_report",
    "write_breadth_sensitivity_summary",
    "write_boom_ending_candidate_scores",
    "write_boom_ending_diagnostics",
    "write_boom_ending_attribution",
    "write_candidate_indicator_scores",
    "write_candidate_recession_diagnostics",
    "write_candidate_recession_rule_report",
    "write_candidate_recession_overlay_report",
]
